### ISSUE TITLE
jake db:create does not return error on failure

### ISSUE THREAD

**Issue by BenBE** [Chaotikum/icebox-service#14]
When running ```jake db:create``` the exit code is 0 even if the overall process failed.

```
$ NODE_PATH=/usr/lib/nodejs jake db:create
Create tables
Could not connect to postgres { Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }
$ echo $?
0
```

Expected behaviour: Return non-zero on failure.

**Comment by BenBE** [comment]
Investigating this, the solution might be something along the lines of this:
https://github.com/jakejs/jake/issues/337
